#!/bin/sh
# ****************************************************************************
# Script created to navigate SVN repositories intuitively
# Executing it creates an environment which appends any commands to the SVN command
# ****************************************************************************

function add_svn_cmd {
  local command="svn "

  if [[ "$1" == "svn" ]]; then
    # Remove the first argument from the command line
    shift
  fi
  
  if [[ "$1" == "exit" ]]; then
    exit
  fi

  local input="$@"
  output_command+=$input
  echo $output_command
}

echo "Welcome to the SVN command line interface! Please enter your username"
read -r -p Username:
read -p Password:

echo "Welcome to the SVN CLI. Use help for info on the commands. Use \"exit\" or Ctrl+C to leave the CLI"
while true
do
  read -p svncli: -e svn_arg
  full_command=$(add_svn_cmd $svn_arg)
  (exec $full_command)
done
